name: Run Jest Tests and Send Results

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --json --outputFile=jest-results.json

      - name: Read Jest results file3
        id: read-results
        run: |
          echo "::set-output name=results::$(jq -Rs '.' jest-results.json)"

      - name: Send test results to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '${{ steps.read-results.outputs.results }}' "https://webhook.site/d60cc8fd-496c-4d4d-b0ed-32ed274cc7df"
