name: Run Jest Tests and Send Results

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --json --outputFile=jest-results.json

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read Jest results file
        id: read-results
        run: |
          JSON_RESULTS=$(jq -c '.' jest-results.json)
          JSON_RESULTS_ESCAPED=$(echo $JSON_RESULTS | sed 's/"/\\"/g')
          echo "::set-output name=results::$JSON_RESULTS_ESCAPED"

      - name: Send test results to webhook
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"github_user\": \"$GITHUB_ACTOR\", \"missionId\": \"JHMWMIPj9tXj7z7Eums5\", \"test_results\": \"${{ steps.read-results.outputs.results }}\"}" \
               "https://us-central1-radicalx-68127.cloudfunctions.net/githubActionsWebhook"
