name: Run Jest Tests and Send Results

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test -- --json --outputFile=jest-results.json

      - name: Install jq
        run: sudo apt-get install jq

      - name: Read Jest results file
        id: read-results
        run: |
          JSON_RESULTS=$(jq -cM '.' jest-results.json)
          echo "::set-output name=results::$JSON_RESULTS"

      - name: Generate payload
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        id: payload
        run: |
          PAYLOAD=$(printf '{"github_user": "%s", "missionId": "JHMWMIPj9tXj7z7Eums5", "test_results": %s}' "$GITHUB_ACTOR" "${{ steps.read-results.outputs.results }}")
          echo "$PAYLOAD" > payload.json

      - name: Display payload
        run: cat payload.json

      - name: Send test results to webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
               --data-binary @payload.json \
               "https://us-central1-radicalx-68127.cloudfunctions.net/githubActionsWebhook"
